toc: true
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 你是无意穿堂风，<br>偏偏孤倨引山洪。
    bannerText: welcome to my blog!
sidebar:
  typedTextPrefix: I`m
  typedText: ["Data Developer"]
user:
  name: 两人从
  first_name: 两
  last_name: 人从
  email: wqkenqingto@163.com
  domain: www.wqkenqing.ren
  avatar: https://pics2.baidu.com/feed/18d8bc3eb13533fa66d9dfd449aa8c1640345b64.jpeg@f_auto?token=00dece5fb8e88b9d32b977d0cae4e001
  describe: 记录。