toc: true
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 你是无意穿堂风，<br>偏偏孤倨引山洪。
    bannerText: welcome to my blog!
sidebar:
  typedTextPrefix: I`m
  typedText: [" Developer"]