toc: true
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 你是无意穿堂风，<br>偏偏孤倨引。
    bannerText: Hi my new friend!