blank_issues_enabled: false
contact_links:
  - name: Questions about Hexo-Theme-Asycn
    url: https://github.com/MaLuns/hexo-theme-async/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.

  # - name: QQ 群
  #   url: https://jq.qq.com/?_wv=1027&k=0hEe5D0U
  #   about: '群号 726491833'