version: "2.3"
services:
  sjksh-store-info:
    image: registry.lisong.pub:28500/hy/hy-sjksh-info-dev-v6
    container_name: hy-sjksh-info-dev
    cpus: 2
    mem_limit: 2g
    restart: unless-stopped
    extra_hosts:
        - "namenode:192.168.10.100"
        - "datanode1:192.168.10.101"
        - "datanode2:192.168.10.102"
        - "datanode3:192.168.10.103"
        - "namenode2:192.168.10.104"
    env_file:
      - common.env
    environment:
      - JAVA_OPTIONS=-XX:CompressedClassSpaceSize=32m
